version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: bestuser
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
      MYSQL_DATABASE: wildcards_schema
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "db" ]
      timeout: 20s
      retries: 10
  app:
    build: .\JJDZR12-WildcardsWeb\
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy