spring:
  datasource:
    url: jdbc:mysql://83.25.29.44:3306/wildcards_schema?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

logging:
  config: classpath:logback.xml