spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wildcards_schema?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080