spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wildcards_schema
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false


  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:logback.xml